# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R for our teams
email: 
description: by Nistara Randhawa and Elizabeth VanWormer
baseurl: "/R-for-PREDICT-and-VISHA" # the subpath of your site, e.g. /blog
url: "http://nistara.github.io/R-for-our-teams" # the base hostname & protocol for your site
github_username:  nistara

# Build settings
markdown: kramdown
